/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as UnauthenticatedIndexRouteImport } from './routes/_unauthenticated/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as UnauthenticatedAuthCallbackRouteImport } from './routes/_unauthenticated/auth/callback'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users/$userId'
import { Route as AuthenticatedImportsResidentRouteImport } from './routes/_authenticated/imports/resident'
import { Route as AuthenticatedCondominiumsCreateRouteImport } from './routes/_authenticated/condominiums/create'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedIndexRoute = UnauthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const UnauthenticatedAuthCallbackRoute =
  UnauthenticatedAuthCallbackRouteImport.update({
    id: '/auth/callback',
    path: '/auth/callback',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportsResidentRoute =
  AuthenticatedImportsResidentRouteImport.update({
    id: '/imports/resident',
    path: '/imports/resident',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCondominiumsCreateRoute =
  AuthenticatedCondominiumsCreateRouteImport.update({
    id: '/condominiums/create',
    path: '/condominiums/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof UnauthenticatedIndexRoute
  '/condominiums/create': typeof AuthenticatedCondominiumsCreateRoute
  '/imports/resident': typeof AuthenticatedImportsResidentRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/auth/callback': typeof UnauthenticatedAuthCallbackRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof UnauthenticatedIndexRoute
  '/condominiums/create': typeof AuthenticatedCondominiumsCreateRoute
  '/imports/resident': typeof AuthenticatedImportsResidentRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/auth/callback': typeof UnauthenticatedAuthCallbackRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_unauthenticated/': typeof UnauthenticatedIndexRoute
  '/_authenticated/condominiums/create': typeof AuthenticatedCondominiumsCreateRoute
  '/_authenticated/imports/resident': typeof AuthenticatedImportsResidentRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_unauthenticated/auth/callback': typeof UnauthenticatedAuthCallbackRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/condominiums/create'
    | '/imports/resident'
    | '/users/$userId'
    | '/auth/callback'
    | '/dashboard/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/condominiums/create'
    | '/imports/resident'
    | '/users/$userId'
    | '/auth/callback'
    | '/dashboard'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_unauthenticated/'
    | '/_authenticated/condominiums/create'
    | '/_authenticated/imports/resident'
    | '/_authenticated/users/$userId'
    | '/_unauthenticated/auth/callback'
    | '/_authenticated/dashboard/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/': {
      id: '/_unauthenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedIndexRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_unauthenticated/auth/callback': {
      id: '/_unauthenticated/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof UnauthenticatedAuthCallbackRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/imports/resident': {
      id: '/_authenticated/imports/resident'
      path: '/imports/resident'
      fullPath: '/imports/resident'
      preLoaderRoute: typeof AuthenticatedImportsResidentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/condominiums/create': {
      id: '/_authenticated/condominiums/create'
      path: '/condominiums/create'
      fullPath: '/condominiums/create'
      preLoaderRoute: typeof AuthenticatedCondominiumsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCondominiumsCreateRoute: typeof AuthenticatedCondominiumsCreateRoute
  AuthenticatedImportsResidentRoute: typeof AuthenticatedImportsResidentRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCondominiumsCreateRoute: AuthenticatedCondominiumsCreateRoute,
  AuthenticatedImportsResidentRoute: AuthenticatedImportsResidentRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedIndexRoute: typeof UnauthenticatedIndexRoute
  UnauthenticatedAuthCallbackRoute: typeof UnauthenticatedAuthCallbackRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedIndexRoute: UnauthenticatedIndexRoute,
  UnauthenticatedAuthCallbackRoute: UnauthenticatedAuthCallbackRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
